### ISSUE TITLE
Some options for BossMod

### ISSUE THREAD

**Issue by ghost** [awgil/ffxiv_plugin_distribution#1]
Sorry if this isn't the right place, I wasn't able to find a repo for BossMod.

1) An option to hide the underlying Movement Hint window

This would leave the map still visible, but the black window underneath would be invisible

2) An option to disable the rotation of the Movement Hint map

Should probably lock to North, or maybe have an option for what direction to lock it to.

3) Transparency options for the Movement Hints

This would be helpful for option 1). Without the window underneath sometimes the transparency would make ground aoes hard to see on the map.

**Comment by awgil** [comment]
Wow how did you even find this :D

This is currently very alpha quality, but feel free to try using it and report any bugs or feature requests. I'll push the main plugin repo later today and will leave a link.

Regarding issues you've reported - will implement.

**Comment by ghost** [comment]
I found the repo through the DalamudRepoBrowser plugin, it's been up there for about a week (I assume it scours github for dalamud projects and automatically adds them). I installed BossMods and thought it was kinda neat so I followed the repo link to find if there was anything else and then I ended up here.

**Comment by awgil** [comment]
Added option for #2 (/vbm -> Boss modules settings -> Rotate map to match camera orientation).

Pushed plugin repo to github and added a link in the plugin (https://github.com/awgil/ffxiv_bossmod).

#1 - did a quick experiment and it looked like shit :D will experiment more later, or you can try tweaking it yourself and submitting a PR if you can make it look good...

**Comment by ghost** [comment]
What do you do to test the plugin? Thus far I've just been testing it whenever I'm doing PF Savage but being able to test it outside of that would be nice.

**Comment by ghost** [comment]
As for transparency on the window, in an early version of this plugin you were able to make the Boss module window as small as you liked and making it so small that it was basically invisible looked fine to me back then. At some point a minimum size was added to the window though.

**Comment by awgil** [comment]
For testing - there are two ways. Most of development and testing is done out of game, solution in main plugin repo has special UIDev project for that. In-game, you can activate any bossmod using "/vbm z zone-ID" command. You can look up BossModuleManager.cs for a list of zones and associated modules.

**Comment by ghost** [comment]
I tried playing around a little bit but I really have no idea what I'm doing lol. I added some ImGui window flags to make the window transparent and commented out the code that adds all the buttons and text and stuff just to test and it looks fine to me. Just the map and hints with no background which is exactly what I wanted. It's not a real solution since it's not toggleable but it works enough for me.

![image](https://user-images.githubusercontent.com/55117631/153846755-d1398b1b-49be-4316-a3f6-7fb72f926c95.png)

![image](https://user-images.githubusercontent.com/55117631/153848003-0bcd2d5a-a732-421c-90d1-d123e4ccd05e.png)

**Comment by awgil** [comment]
#1 and #3 are fixed - look for "Trisha mode" in config (don't ask) + added scale slider.

I think this is all, closing this issue....

**Comment by ghost** [comment]
Looks great! Love the size customization too. Thanks.
